### ISSUE TITLE
What if my request is blocked?

### ISSUE THREAD

**Issue by mateuszbuda** [Cybrarist/Discount-Bandit#2]
**Is your feature request related to a problem? Please describe.**
When I configure many products or want to check for prices more frequently and I host the instance from my IP or some datacenter cloud IP, I can get detected by Amazon and get my requests blocked. Is there any remedy for this?

**Describe the solution you'd like**
Having an option to connect using some kind of a proxy service or web scraping API would be ideal.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Cybrarist** [comment]
so you're planning to build another camelcamelcamel? 

i won't do this sadly, i don't want people to abuse this and then amazon strike the software down, i've tried it with max 60 products and it was working perfectly, sometimes it gets blocked but then it works after 10 mins.

so i don't really wanna help people to abuse amazon or other future stores' services otherwise they'll just make it harder for everyone to scrap.

i can make  something that will let the software pause scraping for like 10mins and then continue from where it paused. 

you are welcome to fork the project and add your own proxy if you're planning to scale it
