### ISSUE TITLE
Telegram Notification and Deals For Affiliate

### ISSUE THREAD

**Issue by rokipet** [Cybrarist/Discount-Bandit#7]
Would be nice to add that and have each channel from telegram to get notification with the pictures and picture and prices also  scrape if any product changes drastically to 1 dolar or 0 dolar by categories   scan for flash deals

**Comment by Cybrarist** [comment]
i don't see a usage for this for the normal user tbh,if you have a case for it, feel free to reply otherwise if you want to make it for telegram channels you are always welcome to fork the code and implement the feature. 

in regards to product changes, you can either use the price target, which let's say the usual price is 100, you can put it at 99. then you will be notified when the price is changed by 1.

not sure what you mean by categories scan but if you mean that the app will scan whole category page and get the products, then i can't do that. amazon can easily flag this behavior, so, it doesn't make sense to implement it since the rate is 60 products per 5 mins which i think is more than enough.

**Comment by Cybrarist** [comment]
closed as this won't supported by software.
